{
 "title": "gRPC-Core Experiments - Performance Dashboard",
 "time": { "from": "now-14d", "to": "now" },
 "panels": [
  {
   "title": "Unary secure ping pong median latency - Language comparison (in microsec)",
   "type": "graph",
   "description": "Language comparison of unary ping pong between two GKE nodes in the same cluster (each node resides on a separate VM, both VMs are located in the same compute zone). Secure connection is used.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  (metadata->>'created')::timestamp AS time,\n  'baseline' AS metric,\n  MAX(CAST(summary->>'latency50' AS DOUBLE PRECISION) / 1000) as latency_us\nFROM\n ci_master_results_8core\nWHERE\n $__timeFilter(metadata->>'created') AND\n scenario->>'name' = 'cpp_protobuf_sync_unary_ping_pong_secure'\n GROUP BY\n     time, metric;"
    },
    {
     "rawSql": "SELECT\n  (metadata->>'created')::timestamp AS time,\n  'event_engine_listener' AS metric,\n  MAX(CAST(summary->>'latency50' AS DOUBLE PRECISION) / 1000) as latency_us\nFROM\n results_8core_event_engine_listener\nWHERE\n $__timeFilter(metadata->>'created') AND\n scenario->>'name' = 'cpp_protobuf_sync_unary_ping_pong_secure'\n GROUP BY\n     time, metric;"
    },
    {
     "rawSql": "SELECT\n  (metadata->>'created')::timestamp AS time,\n  'work_stealing' AS metric,\n  MAX(CAST(summary->>'latency50' AS DOUBLE PRECISION) / 1000) as latency_us\nFROM\n results_8core_work_stealing\nWHERE\n $__timeFilter(metadata->>'created') AND\n scenario->>'name' = 'cpp_protobuf_sync_unary_ping_pong_secure'\n GROUP BY\n     time, metric;"
    }
   ]
  },
  {
   "title": "Streaming secure ping pong median latency (in microsec)",
   "type": "graph",
   "description": "Language comparison of streaming ping pong between two GKE nodes in the same cluster (each node resides on a separate VM, both VMs are located in the same compute zone). Secure connection is used.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n    (metadata->>'created')::timestamp AS \"time\",\n    'baseline' as metric,\n    MAX(CAST(summary->>'latency50' AS DOUBLE PRECISION) / 1000) as latency_us\nFROM ci_master_results_8core\nWHERE\n  $__timeFilter(metadata->>'created') AND\n  scenario->>'name' = 'cpp_protobuf_async_streaming_ping_pong_secure'\nGROUP BY\n  \"time\", metric;"
    },
    {
     "rawSql": "SELECT\n    (metadata->>'created')::timestamp AS \"time\",\n    'event_engine_listener' as metric,\n    MAX(CAST(summary->>'latency50' AS DOUBLE PRECISION) / 1000) as latency_us\nFROM results_8core_event_engine_listener\nWHERE\n  $__timeFilter(metadata->>'created') AND\n  scenario->>'name' = 'cpp_protobuf_async_streaming_ping_pong_secure'\nGROUP BY\n  \"time\", metric;"
    },
    {
     "rawSql": "SELECT\n    (metadata->>'created')::timestamp AS \"time\",\n    'work_stealing' as metric,\n    MAX(CAST(summary->>'latency50' AS DOUBLE PRECISION) / 1000) as latency_us\nFROM results_8core_work_stealing\nWHERE\n  $__timeFilter(metadata->>'created') AND\n  scenario->>'name' = 'cpp_protobuf_async_streaming_ping_pong_secure'\nGROUP BY\n  \"time\", metric;"
    }
   ]
  },
  {
   "title": "Unary secure throughput QPS (8 core client to 8 core server)",
   "type": "graph",
   "description": "Throughput as number of unary RPCs per second between two GKE nodes in the same cluster (each node resides on a separate 8core VM, both VMs are located in the same compute zone). Secure connection is used.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n    (metadata->>'created')::timestamp AS \"time\",\n    'baseline' as metric,\n    MIN(ROUND(CAST(summary->>'qps' AS DOUBLE PRECISION))) as throughput_qps\nFROM ci_master_results_8core\nWHERE\n  $__timeFilter(metadata->>'created') AND\n  scenario->>'name' = 'cpp_protobuf_async_unary_qps_unconstrained_secure'\nGROUP BY\n  \"time\", metric;"
    },
    {
     "rawSql": "SELECT\n    (metadata->>'created')::timestamp AS \"time\",\n    'event_engine_listener' as metric,\n    MIN(ROUND(CAST(summary->>'qps' AS DOUBLE PRECISION))) as throughput_qps\nFROM results_8core_event_engine_listener\nWHERE\n  $__timeFilter(metadata->>'created') AND\n  scenario->>'name' = 'cpp_protobuf_async_unary_qps_unconstrained_secure'\nGROUP BY\n  \"time\", metric;"
    },
    {
     "rawSql": "SELECT\n    (metadata->>'created')::timestamp AS \"time\",\n    'work_stealing' as metric,\n    MIN(ROUND(CAST(summary->>'qps' AS DOUBLE PRECISION))) as throughput_qps\nFROM results_8core_work_stealing\nWHERE\n  $__timeFilter(metadata->>'created') AND\n  scenario->>'name' = 'cpp_protobuf_async_unary_qps_unconstrained_secure'\nGROUP BY\n  \"time\", metric;"
    }
   ]
  },
  {
   "title": "Unary secure server CPU (8 core client to 8 core server)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n    (metadata->>'created')::timestamp AS \"time\",\n    'baseline' as metric,\n    MAX(ROUND(CAST(summary->>'serverSystemTime' AS DOUBLE PRECISION) + CAST(summary->>'serverUserTime' AS DOUBLE PRECISION))) / 100 as server_cpu\nFROM ci_master_results_8core\nWHERE\n  $__timeFilter(metadata->>'created') AND\n  scenario->>'name' = 'cpp_protobuf_async_unary_qps_unconstrained_secure'\nGROUP BY\n  \"time\", metric;"
    },
    {
     "rawSql": "SELECT\n    (metadata->>'created')::timestamp AS \"time\",\n    'event_engine_listener' as metric,\n    MAX(ROUND(CAST(summary->>'serverSystemTime' AS DOUBLE PRECISION) + CAST(summary->>'serverUserTime' AS DOUBLE PRECISION))) / 100 as server_cpu\nFROM results_8core_event_engine_listener\nWHERE\n  $__timeFilter(metadata->>'created') AND\n  scenario->>'name' = 'cpp_protobuf_async_unary_qps_unconstrained_secure'\nGROUP BY\n  \"time\", metric;"
    },
    {
     "rawSql": "SELECT\n    (metadata->>'created')::timestamp AS \"time\",\n    'work_stealing' as metric,\n    MAX(ROUND(CAST(summary->>'serverSystemTime' AS DOUBLE PRECISION) + CAST(summary->>'serverUserTime' AS DOUBLE PRECISION))) / 100 as server_cpu\nFROM results_8core_work_stealing\nWHERE\n  $__timeFilter(metadata->>'created') AND\n  scenario->>'name' = 'cpp_protobuf_async_unary_qps_unconstrained_secure'\nGROUP BY\n  \"time\", metric;"
    }
   ]
  },
  {
   "title": "Unary secure client CPU (8 core client to 8 core server)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n    (metadata->>'created')::timestamp AS \"time\",\n    'baseline' as metric,\n    MAX(ROUND(CAST(summary->>'clientSystemTime' AS DOUBLE PRECISION) + CAST(summary->>'clientUserTime' AS DOUBLE PRECISION)) / 100) as client_cpu\nFROM ci_master_results_8core\nWHERE\n  $__timeFilter(metadata->>'created') AND\n  scenario->>'name' = 'cpp_protobuf_async_unary_qps_unconstrained_secure'\nGROUP BY\n  \"time\", metric;"
    },
    {
     "rawSql": "SELECT\n    (metadata->>'created')::timestamp AS \"time\",\n    'event_engine_listener' as metric,\n    MAX(ROUND(CAST(summary->>'clientSystemTime' AS DOUBLE PRECISION) + CAST(summary->>'clientUserTime' AS DOUBLE PRECISION)) / 100) as client_cpu\nFROM results_8core_event_engine_listener\nWHERE\n  $__timeFilter(metadata->>'created') AND\n  scenario->>'name' = 'cpp_protobuf_async_unary_qps_unconstrained_secure'\nGROUP BY\n  \"time\", metric;"
    },
    {
     "rawSql": "SELECT\n    (metadata->>'created')::timestamp AS \"time\",\n    'work_stealing' as metric,\n    MAX(ROUND(CAST(summary->>'clientSystemTime' AS DOUBLE PRECISION) + CAST(summary->>'clientUserTime' AS DOUBLE PRECISION)) / 100) as client_cpu\nFROM results_8core_work_stealing\nWHERE\n  $__timeFilter(metadata->>'created') AND\n  scenario->>'name' = 'cpp_protobuf_async_unary_qps_unconstrained_secure'\nGROUP BY\n  \"time\", metric;"
    }
   ]
  },
  {
   "title": "Streaming secure throughput QPS (8 core client to 8 core server)",
   "type": "graph",
   "description": "Throughput as streaming ping-pong operations per second between two GKE nodes in the same cluster (each node resides on a separate 8core VM, both VMs are located in the same compute zone). Secure connection is used.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n    (metadata->>'created')::timestamp AS \"time\",\n    'baseline' as metric,\n    MIN(ROUND(CAST(summary->>'qps' AS DOUBLE PRECISION))) as throughput_qps\nFROM ci_master_results_8core\nWHERE\n  $__timeFilter(metadata->>'created') AND\n  scenario->>'name' = 'cpp_protobuf_async_streaming_qps_unconstrained_secure'\nGROUP BY\n  \"time\", metric;"
    },
    {
     "rawSql": "SELECT\n    (metadata->>'created')::timestamp AS \"time\",\n    'event_engine_listener' as metric,\n    MIN(ROUND(CAST(summary->>'qps' AS DOUBLE PRECISION))) as throughput_qps\nFROM results_8core_event_engine_listener\nWHERE\n  $__timeFilter(metadata->>'created') AND\n  scenario->>'name' = 'cpp_protobuf_async_streaming_qps_unconstrained_secure'\nGROUP BY\n  \"time\", metric;"
    },
    {
     "rawSql": "SELECT\n    (metadata->>'created')::timestamp AS \"time\",\n    'work_stealing' as metric,\n    MIN(ROUND(CAST(summary->>'qps' AS DOUBLE PRECISION))) as throughput_qps\nFROM results_8core_work_stealing\nWHERE\n  $__timeFilter(metadata->>'created') AND\n  scenario->>'name' = 'cpp_protobuf_async_streaming_qps_unconstrained_secure'\nGROUP BY\n  \"time\", metric;"
    }
   ]
  },
  {
   "title": "Streaming secure server CPU (8 core client to 8 core server)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n    (metadata->>'created')::timestamp AS \"time\",\n    'baseline' as metric,\n    MAX(ROUND(CAST(summary->>'serverSystemTime' AS DOUBLE PRECISION) + CAST(summary->>'serverUserTime' AS DOUBLE PRECISION))) / 100 as server_cpu\nFROM ci_master_results_8core\nWHERE\n  $__timeFilter(metadata->>'created') AND\n  scenario->>'name' = 'cpp_protobuf_async_streaming_qps_unconstrained_secure'\nGROUP BY\n  \"time\", metric;"
    },
    {
     "rawSql": "SELECT\n    (metadata->>'created')::timestamp AS \"time\",\n    'event_engine_listener' as metric,\n    MAX(ROUND(CAST(summary->>'serverSystemTime' AS DOUBLE PRECISION) + CAST(summary->>'serverUserTime' AS DOUBLE PRECISION))) / 100 as server_cpu\nFROM results_8core_event_engine_listener\nWHERE\n  $__timeFilter(metadata->>'created') AND\n  scenario->>'name' = 'cpp_protobuf_async_streaming_qps_unconstrained_secure'\nGROUP BY\n  \"time\", metric;"
    },
    {
     "rawSql": "SELECT\n    (metadata->>'created')::timestamp AS \"time\",\n    'work_stealing' as metric,\n    MAX(ROUND(CAST(summary->>'serverSystemTime' AS DOUBLE PRECISION) + CAST(summary->>'serverUserTime' AS DOUBLE PRECISION))) / 100 as server_cpu\nFROM results_8core_work_stealing\nWHERE\n  $__timeFilter(metadata->>'created') AND\n  scenario->>'name' = 'cpp_protobuf_async_streaming_qps_unconstrained_secure'\nGROUP BY\n  \"time\", metric;"
    }
   ]
  },
  {
   "title": "Streaming secure client CPU (8 core client to 8 core server)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n    (metadata->>'created')::timestamp AS \"time\",\n    'baseline' as metric,\n    MAX(ROUND(CAST(summary->>'clientSystemTime' AS DOUBLE PRECISION) + CAST(summary->>'clientUserTime' AS DOUBLE PRECISION)) / 100) as client_cpu\nFROM ci_master_results_8core\nWHERE\n  $__timeFilter(metadata->>'created') AND\n  scenario->>'name' = 'cpp_protobuf_async_streaming_qps_unconstrained_secure'\nGROUP BY\n  \"time\", metric;"
    },
    {
     "rawSql": "SELECT\n    (metadata->>'created')::timestamp AS \"time\",\n    'event_engine_listener' as metric,\n    MAX(ROUND(CAST(summary->>'clientSystemTime' AS DOUBLE PRECISION) + CAST(summary->>'clientUserTime' AS DOUBLE PRECISION)) / 100) as client_cpu\nFROM results_8core_event_engine_listener\nWHERE\n  $__timeFilter(metadata->>'created') AND\n  scenario->>'name' = 'cpp_protobuf_async_streaming_qps_unconstrained_secure'\nGROUP BY\n  \"time\", metric;"
    },
    {
     "rawSql": "SELECT\n    (metadata->>'created')::timestamp AS \"time\",\n    'work_stealing' as metric,\n    MAX(ROUND(CAST(summary->>'clientSystemTime' AS DOUBLE PRECISION) + CAST(summary->>'clientUserTime' AS DOUBLE PRECISION)) / 100) as client_cpu\nFROM results_8core_work_stealing\nWHERE\n  $__timeFilter(metadata->>'created') AND\n  scenario->>'name' = 'cpp_protobuf_async_streaming_qps_unconstrained_secure'\nGROUP BY\n  \"time\", metric;"
    }
   ]
  },
  {
   "title": "Unary secure throughput QPS (32 core client to 32 core server)",
   "type": "graph",
   "description": "Throughput as number of unary RPCs per second between two GKE nodes in the same cluster (each node resides on a separate 32core VM, both VMs are located in the same compute zone). Secure connection is used.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n    (metadata->>'created')::timestamp AS \"time\",\n    'baseline' as metric,\n    MIN(ROUND(CAST(summary->>'qps' AS DOUBLE PRECISION))) as throughput_qps\nFROM ci_master_results_32core\nWHERE\n  $__timeFilter(metadata->>'created') AND\n  scenario->>'name' = 'cpp_protobuf_async_unary_qps_unconstrained_secure'\nGROUP BY\n  \"time\", metric;"
    },
    {
     "rawSql": "SELECT\n    (metadata->>'created')::timestamp AS \"time\",\n    'event_engine_listener' as metric,\n    MIN(ROUND(CAST(summary->>'qps' AS DOUBLE PRECISION))) as throughput_qps\nFROM results_32core_event_engine_listener\nWHERE\n  $__timeFilter(metadata->>'created') AND\n  scenario->>'name' = 'cpp_protobuf_async_unary_qps_unconstrained_secure'\nGROUP BY\n  \"time\", metric;"
    },
    {
     "rawSql": "SELECT\n    (metadata->>'created')::timestamp AS \"time\",\n    'work_stealing' as metric,\n    MIN(ROUND(CAST(summary->>'qps' AS DOUBLE PRECISION))) as throughput_qps\nFROM results_32core_work_stealing\nWHERE\n  $__timeFilter(metadata->>'created') AND\n  scenario->>'name' = 'cpp_protobuf_async_unary_qps_unconstrained_secure'\nGROUP BY\n  \"time\", metric;"
    }
   ]
  },
  {
   "title": "Unary secure server CPU (32 core client to 32 core server)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n    (metadata->>'created')::timestamp AS \"time\",\n    'baseline' as metric,\n    MAX(ROUND(CAST(summary->>'serverSystemTime' AS DOUBLE PRECISION) + CAST(summary->>'serverUserTime' AS DOUBLE PRECISION))) / 100 as server_cpu\nFROM ci_master_results_32core\nWHERE\n  $__timeFilter(metadata->>'created') AND\n  scenario->>'name' = 'cpp_protobuf_async_unary_qps_unconstrained_secure'\nGROUP BY\n  \"time\", metric;"
    },
    {
     "rawSql": "SELECT\n    (metadata->>'created')::timestamp AS \"time\",\n    'event_engine_listener' as metric,\n    MAX(ROUND(CAST(summary->>'serverSystemTime' AS DOUBLE PRECISION) + CAST(summary->>'serverUserTime' AS DOUBLE PRECISION))) / 100 as server_cpu\nFROM results_32core_event_engine_listener\nWHERE\n  $__timeFilter(metadata->>'created') AND\n  scenario->>'name' = 'cpp_protobuf_async_unary_qps_unconstrained_secure'\nGROUP BY\n  \"time\", metric;"
    },
    {
     "rawSql": "SELECT\n    (metadata->>'created')::timestamp AS \"time\",\n    'work_stealing' as metric,\n    MAX(ROUND(CAST(summary->>'serverSystemTime' AS DOUBLE PRECISION) + CAST(summary->>'serverUserTime' AS DOUBLE PRECISION))) / 100 as server_cpu\nFROM results_32core_work_stealing\nWHERE\n  $__timeFilter(metadata->>'created') AND\n  scenario->>'name' = 'cpp_protobuf_async_unary_qps_unconstrained_secure'\nGROUP BY\n  \"time\", metric;"
    }
   ]
  },
  {
   "title": "Unary secure client CPU (32 core client to 32 core server)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n    (metadata->>'created')::timestamp AS \"time\",\n    'baseline' as metric,\n    MAX(ROUND(CAST(summary->>'clientSystemTime' AS DOUBLE PRECISION) + CAST(summary->>'clientUserTime' AS DOUBLE PRECISION)) / 100) as client_cpu\nFROM ci_master_results_32core\nWHERE\n  $__timeFilter(metadata->>'created') AND\n  scenario->>'name' = 'cpp_protobuf_async_unary_qps_unconstrained_secure'\nGROUP BY\n  \"time\", metric;"
    },
    {
     "rawSql": "SELECT\n    (metadata->>'created')::timestamp AS \"time\",\n    'event_engine_listener' as metric,\n    MAX(ROUND(CAST(summary->>'clientSystemTime' AS DOUBLE PRECISION) + CAST(summary->>'clientUserTime' AS DOUBLE PRECISION)) / 100) as client_cpu\nFROM results_32core_event_engine_listener\nWHERE\n  $__timeFilter(metadata->>'created') AND\n  scenario->>'name' = 'cpp_protobuf_async_unary_qps_unconstrained_secure'\nGROUP BY\n  \"time\", metric;"
    },
    {
     "rawSql": "SELECT\n    (metadata->>'created')::timestamp AS \"time\",\n    'work_stealing' as metric,\n    MAX(ROUND(CAST(summary->>'clientSystemTime' AS DOUBLE PRECISION) + CAST(summary->>'clientUserTime' AS DOUBLE PRECISION)) / 100) as client_cpu\nFROM results_32core_work_stealing\nWHERE\n  $__timeFilter(metadata->>'created') AND\n  scenario->>'name' = 'cpp_protobuf_async_unary_qps_unconstrained_secure'\nGROUP BY\n  \"time\", metric;"
    }
   ]
  },
  {
   "title": "Streaming secure throughput QPS (32 core client to 32 core server)",
   "type": "graph",
   "description": "Throughput as streaming ping-pong operations per second between two GKE nodes in the same cluster (each node resides on a separate 32core VM, both VMs are located in the same compute zone). Secure connection is used.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n    (metadata->>'created')::timestamp AS \"time\",\n    'baseline' as metric,\n    MIN(ROUND(CAST(summary->>'qps' AS DOUBLE PRECISION))) as throughput_qps\nFROM ci_master_results_32core\nWHERE\n  $__timeFilter(metadata->>'created') AND\n  scenario->>'name' = 'cpp_protobuf_async_streaming_qps_unconstrained_secure'\nGROUP BY\n  \"time\", metric;"
    },
    {
     "rawSql": "SELECT\n    (metadata->>'created')::timestamp AS \"time\",\n    'event_engine_listener' as metric,\n    MIN(ROUND(CAST(summary->>'qps' AS DOUBLE PRECISION))) as throughput_qps\nFROM results_32core_event_engine_listener\nWHERE\n  $__timeFilter(metadata->>'created') AND\n  scenario->>'name' = 'cpp_protobuf_async_streaming_qps_unconstrained_secure'\nGROUP BY\n  \"time\", metric;"
    },
    {
     "rawSql": "SELECT\n    (metadata->>'created')::timestamp AS \"time\",\n    'work_stealing' as metric,\n    MIN(ROUND(CAST(summary->>'qps' AS DOUBLE PRECISION))) as throughput_qps\nFROM results_32core_work_stealing\nWHERE\n  $__timeFilter(metadata->>'created') AND\n  scenario->>'name' = 'cpp_protobuf_async_streaming_qps_unconstrained_secure'\nGROUP BY\n  \"time\", metric;"
    }
   ]
  },
  {
   "title": "Streaming secure server CPU (32 core client to 32 core server)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n    (metadata->>'created')::timestamp AS \"time\",\n    'baseline' as metric,\n    MAX(ROUND(CAST(summary->>'serverSystemTime' AS DOUBLE PRECISION) + CAST(summary->>'serverUserTime' AS DOUBLE PRECISION))) / 100 as server_cpu\nFROM ci_master_results_32core\nWHERE\n  $__timeFilter(metadata->>'created') AND\n  scenario->>'name' = 'cpp_protobuf_async_streaming_qps_unconstrained_secure'\nGROUP BY\n  \"time\", metric;"
    },
    {
     "rawSql": "SELECT\n    (metadata->>'created')::timestamp AS \"time\",\n    'event_engine_listener' as metric,\n    MAX(ROUND(CAST(summary->>'serverSystemTime' AS DOUBLE PRECISION) + CAST(summary->>'serverUserTime' AS DOUBLE PRECISION))) / 100 as server_cpu\nFROM results_32core_event_engine_listener\nWHERE\n  $__timeFilter(metadata->>'created') AND\n  scenario->>'name' = 'cpp_protobuf_async_streaming_qps_unconstrained_secure'\nGROUP BY\n  \"time\", metric;"
    },
    {
     "rawSql": "SELECT\n    (metadata->>'created')::timestamp AS \"time\",\n    'work_stealing' as metric,\n    MAX(ROUND(CAST(summary->>'serverSystemTime' AS DOUBLE PRECISION) + CAST(summary->>'serverUserTime' AS DOUBLE PRECISION))) / 100 as server_cpu\nFROM results_32core_work_stealing\nWHERE\n  $__timeFilter(metadata->>'created') AND\n  scenario->>'name' = 'cpp_protobuf_async_streaming_qps_unconstrained_secure'\nGROUP BY\n  \"time\", metric;"
    }
   ]
  },
  {
   "title": "Streaming secure client CPU (32 core client to 32 core server)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n    (metadata->>'created')::timestamp AS \"time\",\n    'baseline' as metric,\n    MAX(ROUND(CAST(summary->>'clientSystemTime' AS DOUBLE PRECISION) + CAST(summary->>'clientUserTime' AS DOUBLE PRECISION)) / 100) as client_cpu\nFROM ci_master_results_32core\nWHERE\n  $__timeFilter(metadata->>'created') AND\n  scenario->>'name' = 'cpp_protobuf_async_streaming_qps_unconstrained_secure'\nGROUP BY\n  \"time\", metric;"
    },
    {
     "rawSql": "SELECT\n    (metadata->>'created')::timestamp AS \"time\",\n    'event_engine_listener' as metric,\n    MAX(ROUND(CAST(summary->>'clientSystemTime' AS DOUBLE PRECISION) + CAST(summary->>'clientUserTime' AS DOUBLE PRECISION)) / 100) as client_cpu\nFROM results_32core_event_engine_listener\nWHERE\n  $__timeFilter(metadata->>'created') AND\n  scenario->>'name' = 'cpp_protobuf_async_streaming_qps_unconstrained_secure'\nGROUP BY\n  \"time\", metric;"
    },
    {
     "rawSql": "SELECT\n    (metadata->>'created')::timestamp AS \"time\",\n    'work_stealing' as metric,\n    MAX(ROUND(CAST(summary->>'clientSystemTime' AS DOUBLE PRECISION) + CAST(summary->>'clientUserTime' AS DOUBLE PRECISION)) / 100) as client_cpu\nFROM results_32core_work_stealing\nWHERE\n  $__timeFilter(metadata->>'created') AND\n  scenario->>'name' = 'cpp_protobuf_async_streaming_qps_unconstrained_secure'\nGROUP BY\n  \"time\", metric;"
    }
   ]
  },
  {
   "title": "Unary secure throughput QPS with 1MB message (8 core client to 8 core server)",
   "type": "graph",
   "description": "Throughput as number of unary RPCs per second between two GKE nodes in the same cluster (each node resides on a separate VM, but both VMs are located in the same compute zone). Secure connection is used. Both request & response are 1MB large.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n    (metadata->>'created')::timestamp AS \"time\",\n    'baseline' as metric,\n    MIN(ROUND(CAST(summary->>'qps' AS DOUBLE PRECISION))) as throughput_qps\nFROM ci_master_results_8core\nWHERE\n  $__timeFilter(metadata->>'created') AND\n  scenario->>'name' = 'cpp_protobuf_async_unary_ping_pong_secure_1MB'\nGROUP BY\n  \"time\", metric;"
    },
    {
     "rawSql": "SELECT\n    (metadata->>'created')::timestamp AS \"time\",\n    'event_engine_listener' as metric,\n    MIN(ROUND(CAST(summary->>'qps' AS DOUBLE PRECISION))) as throughput_qps\nFROM results_8core_event_engine_listener\nWHERE\n  $__timeFilter(metadata->>'created') AND\n  scenario->>'name' = 'cpp_protobuf_async_unary_ping_pong_secure_1MB'\nGROUP BY\n  \"time\", metric;"
    },
    {
     "rawSql": "SELECT\n    (metadata->>'created')::timestamp AS \"time\",\n    'work_stealing' as metric,\n    MIN(ROUND(CAST(summary->>'qps' AS DOUBLE PRECISION))) as throughput_qps\nFROM results_8core_work_stealing\nWHERE\n  $__timeFilter(metadata->>'created') AND\n  scenario->>'name' = 'cpp_protobuf_async_unary_ping_pong_secure_1MB'\nGROUP BY\n  \"time\", metric;"
    }
   ]
  }
 ]
}