{
 "title": "PSM dataplane performance on GKE(@upstream/master)",
 "time": { "from": "2022-02-23T20:55:16.801Z", "to": "2022-08-22T20:55:16.801Z" },
 "panels": [
  {
   "title": "Queries/CPU-Seconds",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queries/CPU-Seconds_Java",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "WITH cpu_prep_temp AS(\nSELECT CAST(summary ->> 'qps' AS DOUBLE PRECISION) as qps, jsonb_array_elements((jsonb_array_elements(clientsprometheusdata::jsonb)->> 'containers')::jsonb)->>'cpuSeconds'AS cpuSeconds, (metadata->>'created')::timestamp AS time, (scenario->>'name') AS metric,\njson_array_elements(clientsprometheusdata) ->>'name'  AS clientName   \nFROM psm_experimental_results_8core \n    WHERE metadata ->> 'jobName' = 'grpc/core/master/linux/grpc_psm_performance_gke_experiment' AND scenario->>'name'= 'java_protobuf_async_unary_5000rpcs_1KB_psm_8channels_16threads_10000load'\n) \nSELECT 'proxied' AS metric, time, qps / NULLIF(SUM(CAST(cpuSeconds AS DOUBLE PRECISION)),0) as value FROM cpu_prep_temp WHERE clientName LIKE '%proxied%'\nGROUP BY clientName, time, metric, qps\nORDER BY time;\n"
      },
      {
       "rawSql": "WITH cpu_prep_temp AS(\nSELECT CAST(summary ->> 'qps' AS DOUBLE PRECISION) as qps, jsonb_array_elements((jsonb_array_elements(clientsprometheusdata::jsonb)->> 'containers')::jsonb)->>'cpuSeconds'AS cpuSeconds, (metadata->>'created')::timestamp AS time, (scenario->>'name') AS metric,\njson_array_elements(clientsprometheusdata) ->>'name'  AS clientName   \nFROM psm_experimental_results_8core \n    WHERE metadata ->> 'jobName' = 'grpc/core/master/linux/grpc_psm_performance_gke_experiment' AND scenario->>'name'= 'java_protobuf_async_unary_5000rpcs_1KB_psm_8channels_16threads_10000load'\n) \nSELECT 'proxyless' AS metric, time, qps /NULLIF( SUM(CAST(cpuSeconds AS DOUBLE PRECISION)) ,0)as value FROM cpu_prep_temp WHERE clientName LIKE '%proxyless%'\nGROUP BY clientName, time, metric, qps\nORDER BY time;\n"
      },
      {
       "rawSql": "WITH cpu_prep_temp AS(\nSELECT CAST(summary ->> 'qps' AS DOUBLE PRECISION) as qps, jsonb_array_elements((jsonb_array_elements(clientsprometheusdata::jsonb)->> 'containers')::jsonb)->>'cpuSeconds'AS cpuSeconds, (metadata->>'created')::timestamp AS time, (scenario->>'name') AS metric,\njson_array_elements(clientsprometheusdata) ->>'name'  AS clientName   \nFROM psm_experimental_results_8core \n    WHERE metadata ->> 'jobName' = 'grpc/core/master/linux/grpc_psm_performance_gke_experiment' AND scenario->>'name'= 'java_protobuf_async_unary_5000rpcs_1KB_psm_8channels_16threads_10000load'\n) \nSELECT 'regular' AS metric, time, qps / NULLIF(SUM(CAST(cpuSeconds AS DOUBLE PRECISION)) ,0) as value FROM cpu_prep_temp WHERE clientName LIKE '%regular%'\nGROUP BY clientName, time, metric, qps\nORDER BY time;\n\n"
      }
     ]
    },
    {
     "title": "Queries/CPU-Seconds_cpp",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "WITH cpu_prep_temp AS(\nSELECT CAST(summary ->> 'qps' AS DOUBLE PRECISION) as qps, jsonb_array_elements((jsonb_array_elements(clientsprometheusdata::jsonb)->> 'containers')::jsonb)->>'cpuSeconds'AS cpuSeconds, (metadata->>'created')::timestamp AS time, (scenario->>'name') AS metric,\njson_array_elements(clientsprometheusdata) ->>'name'  AS clientName   \nFROM psm_experimental_results_8core \n    WHERE metadata ->> 'jobName' = 'grpc/core/master/linux/grpc_psm_performance_gke_experiment' AND scenario->>'name'= 'cpp_protobuf_async_unary_5000rpcs_1KB_psm_8channels_16threads_10000load'\n) \nSELECT 'proxied' AS metric, time, qps / NULLIF(SUM(CAST(cpuSeconds AS DOUBLE PRECISION)), 0) as value FROM cpu_prep_temp WHERE clientName LIKE '%proxied%'\nGROUP BY clientName, time, metric, qps\nORDER BY time;\n"
      },
      {
       "rawSql": "WITH cpu_prep_temp AS(\nSELECT CAST(summary ->> 'qps' AS DOUBLE PRECISION) as qps, jsonb_array_elements((jsonb_array_elements(clientsprometheusdata::jsonb)->> 'containers')::jsonb)->>'cpuSeconds'AS cpuSeconds, (metadata->>'created')::timestamp AS time, (scenario->>'name') AS metric,\njson_array_elements(clientsprometheusdata) ->>'name'  AS clientName   \nFROM psm_experimental_results_8core \n    WHERE metadata ->> 'jobName' = 'grpc/core/master/linux/grpc_psm_performance_gke_experiment' AND scenario->>'name'= 'cpp_protobuf_async_unary_5000rpcs_1KB_psm_8channels_16threads_10000load'\n) \nSELECT 'proxyless' AS metric, time, qps /NULLIF( SUM(CAST(cpuSeconds AS DOUBLE PRECISION)) ,0)as value FROM cpu_prep_temp WHERE clientName LIKE '%proxyless%'\nGROUP BY clientName, time, metric, qps\nORDER BY time;\n"
      },
      {
       "rawSql": "WITH cpu_prep_temp AS(\nSELECT CAST(summary ->> 'qps' AS DOUBLE PRECISION) as qps, jsonb_array_elements((jsonb_array_elements(clientsprometheusdata::jsonb)->> 'containers')::jsonb)->>'cpuSeconds'AS cpuSeconds, (metadata->>'created')::timestamp AS time, (scenario->>'name') AS metric,\njson_array_elements(clientsprometheusdata) ->>'name'  AS clientName   \nFROM psm_experimental_results_8core \n    WHERE metadata ->> 'jobName' = 'grpc/core/master/linux/grpc_psm_performance_gke_experiment' AND scenario->>'name'= 'cpp_protobuf_async_unary_5000rpcs_1KB_psm_8channels_16threads_10000load'\n) \nSELECT 'regular' AS metric, time, qps / NULLIF(SUM(CAST(cpuSeconds AS DOUBLE PRECISION)) ,0) as value FROM cpu_prep_temp WHERE clientName LIKE '%regular%'\nGROUP BY clientName, time, metric, qps\nORDER BY time;\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory_java",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "WITH cpu_prep_temp AS(\nSELECT jsonb_array_elements((jsonb_array_elements(clientsprometheusdata::jsonb)->> 'containers')::jsonb)->>'memoryMean' AS memoryMean, (metadata->>'created')::timestamp AS time, (scenario->>'name') AS metric,\njson_array_elements(clientsprometheusdata) ->>'name'  AS clientName   \nFROM psm_experimental_results_8core \n    WHERE metadata ->> 'jobName' = 'grpc/core/master/linux/grpc_psm_performance_gke_experiment' AND scenario->>'name'= 'java_protobuf_async_unary_5000rpcs_1KB_psm_8channels_16threads_10000load'\n) \nSELECT 'proxied' AS metric, time, SUM(CAST(memoryMean AS DOUBLE PRECISION)) as value FROM cpu_prep_temp WHERE clientName LIKE '%proxied%'\nGROUP BY clientName, time, metric\nORDER BY time;\n"
      },
      {
       "rawSql": "WITH cpu_prep_temp AS(\nSELECT jsonb_array_elements((jsonb_array_elements(clientsprometheusdata::jsonb)->> 'containers')::jsonb)->>'memoryMean' AS memoryMean, (metadata->>'created')::timestamp AS time, (scenario->>'name') AS metric,\njson_array_elements(clientsprometheusdata) ->>'name'  AS clientName   \nFROM psm_experimental_results_8core \n    WHERE metadata ->> 'jobName' = 'grpc/core/master/linux/grpc_psm_performance_gke_experiment' AND scenario->>'name'= 'java_protobuf_async_unary_5000rpcs_1KB_psm_8channels_16threads_10000load'\n) \nSELECT  'proxyless'  AS metric, time, SUM(CAST(memoryMean AS DOUBLE PRECISION)) as value FROM cpu_prep_temp WHERE clientName LIKE '%proxyless%'\nGROUP BY clientName, time, metric\nORDER BY time;\n"
      },
      {
       "rawSql": "WITH cpu_prep_temp AS(\nSELECT jsonb_array_elements((jsonb_array_elements(clientsprometheusdata::jsonb)->> 'containers')::jsonb)->>'memoryMean' AS memoryMean, (metadata->>'created')::timestamp AS time, (scenario->>'name') AS metric,\njson_array_elements(clientsprometheusdata) ->>'name'  AS clientName   \nFROM psm_experimental_results_8core \n    WHERE metadata ->> 'jobName' = 'grpc/core/master/linux/grpc_psm_performance_gke_experiment' AND scenario->>'name'= 'java_protobuf_async_unary_5000rpcs_1KB_psm_8channels_16threads_10000load'\n) \nSELECT 'regular' AS metric, time, SUM(CAST(memoryMean AS DOUBLE PRECISION)) as value FROM cpu_prep_temp WHERE clientName LIKE '%regular%'\nGROUP BY clientName, time, metric\nORDER BY time;\n"
      }
     ]
    },
    {
     "title": "Memory_cpp",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "WITH cpu_prep_temp AS(\nSELECT jsonb_array_elements((jsonb_array_elements(clientsprometheusdata::jsonb)->> 'containers')::jsonb)->>'memoryMean' AS memoryMean, (metadata->>'created')::timestamp AS time, (scenario->>'name') AS metric,\njson_array_elements(clientsprometheusdata) ->>'name'  AS clientName   \nFROM psm_experimental_results_8core \n    WHERE metadata ->> 'jobName' = 'grpc/core/master/linux/grpc_psm_performance_gke_experiment' AND scenario->>'name'= 'cpp_protobuf_async_unary_5000rpcs_1KB_psm_8channels_16threads_10000load'\n) \nSELECT 'proxied' AS metric, time, SUM(CAST(memoryMean AS DOUBLE PRECISION)) as value FROM cpu_prep_temp WHERE clientName LIKE '%proxied%'\nGROUP BY clientName, time, metric\nORDER BY time;\n"
      },
      {
       "rawSql": "WITH cpu_prep_temp AS(\nSELECT jsonb_array_elements((jsonb_array_elements(clientsprometheusdata::jsonb)->> 'containers')::jsonb)->>'memoryMean' AS memoryMean, (metadata->>'created')::timestamp AS time, (scenario->>'name') AS metric,\njson_array_elements(clientsprometheusdata) ->>'name'  AS clientName   \nFROM psm_experimental_results_8core \n    WHERE metadata ->> 'jobName' = 'grpc/core/master/linux/grpc_psm_performance_gke_experiment' AND scenario->>'name'= 'cpp_protobuf_async_unary_5000rpcs_1KB_psm_8channels_16threads_10000load'\n) \nSELECT 'proxyless' AS metric, time, SUM(CAST(memoryMean AS DOUBLE PRECISION)) as value FROM cpu_prep_temp WHERE clientName LIKE '%proxyless%'\nGROUP BY clientName, time, metric\nORDER BY time;\n"
      },
      {
       "rawSql": "WITH cpu_prep_temp AS(\nSELECT jsonb_array_elements((jsonb_array_elements(clientsprometheusdata::jsonb)->> 'containers')::jsonb)->>'memoryMean' AS memoryMean, (metadata->>'created')::timestamp AS time, (scenario->>'name') AS metric,\njson_array_elements(clientsprometheusdata) ->>'name'  AS clientName   \nFROM psm_experimental_results_8core \n    WHERE metadata ->> 'jobName' = 'grpc/core/master/linux/grpc_psm_performance_gke_experiment' AND scenario->>'name'= 'cpp_protobuf_async_unary_5000rpcs_1KB_psm_8channels_16threads_10000load'\n) \nSELECT 'regular' AS metric, time, SUM(CAST(memoryMean AS DOUBLE PRECISION)) as value FROM cpu_prep_temp WHERE clientName LIKE '%regular%'\nGROUP BY clientName, time, metric\nORDER BY time;\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency50_us_java",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "WITH latency_prep_temp AS(\n    SELECT CAST(summary->>'latency50' AS DOUBLE PRECISION) / 1000 as latency50,jsonb_array_elements(clientsprometheusdata::jsonb) ->>'name'  AS clientName, (metadata->>'created')::timestamp AS time\n    FROM psm_experimental_results_8core \n    WHERE metadata ->> 'jobName' = 'grpc/core/master/linux/grpc_psm_performance_gke_experiment' AND scenario->>'name'= 'java_protobuf_async_unary_5000rpcs_1KB_psm_8channels_16threads_10000load'\n)\nSELECT  'proxied' AS metric, time, latency50 as value FROM latency_prep_temp WHERE clientName LIKE '%proxied%' \nORDER BY time\n"
      },
      {
       "rawSql": "WITH latency_prep_temp AS(\n    SELECT CAST(summary->>'latency50' AS DOUBLE PRECISION) / 1000 as latency50,jsonb_array_elements(clientsprometheusdata::jsonb) ->>'name'  AS clientName, (metadata->>'created')::timestamp AS time\n    FROM psm_experimental_results_8core \n    WHERE metadata ->> 'jobName' = 'grpc/core/master/linux/grpc_psm_performance_gke_experiment' AND scenario->>'name'= 'java_protobuf_async_unary_5000rpcs_1KB_psm_8channels_16threads_10000load'\n)\nSELECT  'proxyless' AS metric, time, latency50 as value FROM latency_prep_temp WHERE clientName LIKE '%proxyless%' \nORDER BY time\n"
      },
      {
       "rawSql": "WITH latency_prep_temp AS(\n    SELECT CAST(summary->>'latency50' AS DOUBLE PRECISION) / 1000 as latency50,jsonb_array_elements(clientsprometheusdata::jsonb) ->>'name'  AS clientName, (metadata->>'created')::timestamp AS time\n    FROM psm_experimental_results_8core \n    WHERE metadata ->> 'jobName' = 'grpc/core/master/linux/grpc_psm_performance_gke_experiment' AND scenario->>'name'= 'java_protobuf_async_unary_5000rpcs_1KB_psm_8channels_16threads_10000load'\n)\nSELECT  'regular' AS metric, time, latency50 as value FROM latency_prep_temp WHERE clientName LIKE '%regular%' \nORDER BY time"
      }
     ]
    },
    {
     "title": "Latency50_us_cpp",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "WITH latency_prep_temp AS(\n    SELECT CAST(summary->>'latency50' AS DOUBLE PRECISION) / 1000 as latency50,jsonb_array_elements(clientsprometheusdata::jsonb) ->>'name'  AS clientName, (metadata->>'created')::timestamp AS time\n    FROM psm_experimental_results_8core \n    WHERE metadata ->> 'jobName' = 'grpc/core/master/linux/grpc_psm_performance_gke_experiment' AND scenario->>'name'= 'cpp_protobuf_async_unary_5000rpcs_1KB_psm_8channels_16threads_10000load'\n)\nSELECT  'proxied' AS metric, time, latency50 as value FROM latency_prep_temp WHERE clientName LIKE '%proxied%' \nORDER BY time\n"
      },
      {
       "rawSql": "WITH latency_prep_temp AS(\n    SELECT CAST(summary->>'latency50' AS DOUBLE PRECISION) / 1000 as latency50,jsonb_array_elements(clientsprometheusdata::jsonb) ->>'name'  AS clientName, (metadata->>'created')::timestamp AS time\n    FROM psm_experimental_results_8core \n    WHERE metadata ->> 'jobName' = 'grpc/core/master/linux/grpc_psm_performance_gke_experiment' AND scenario->>'name'= 'cpp_protobuf_async_unary_5000rpcs_1KB_psm_8channels_16threads_10000load'\n)\nSELECT  'proxyless' AS metric, time, latency50 as value FROM latency_prep_temp WHERE clientName LIKE '%proxyless%' \nORDER BY time"
      },
      {
       "rawSql": "WITH latency_prep_temp AS(\n    SELECT CAST(summary->>'latency50' AS DOUBLE PRECISION) / 1000 as latency50,jsonb_array_elements(clientsprometheusdata::jsonb) ->>'name'  AS clientName, (metadata->>'created')::timestamp AS time\n    FROM psm_experimental_results_8core \n    WHERE metadata ->> 'jobName' = 'grpc/core/master/linux/grpc_psm_performance_gke_experiment' AND scenario->>'name'= 'cpp_protobuf_async_unary_5000rpcs_1KB_psm_8channels_16threads_10000load'\n)\nSELECT  'regular' AS metric, time, latency50 as value FROM latency_prep_temp WHERE clientName LIKE '%regular%' \nORDER BY time\n"
      }
     ]
    },
    {
     "title": "Latency90_us_java",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "WITH latency_prep_temp AS(\n    SELECT CAST(summary->>'latency90' AS DOUBLE PRECISION) / 1000 as latency90,jsonb_array_elements(clientsprometheusdata::jsonb) ->>'name'  AS clientName, (metadata->>'created')::timestamp AS time\n    FROM psm_experimental_results_8core \n    WHERE metadata ->> 'jobName' = 'grpc/core/master/linux/grpc_psm_performance_gke_experiment' AND scenario->>'name'= 'java_protobuf_async_unary_5000rpcs_1KB_psm_8channels_16threads_10000load'\n)\nSELECT  'proxied' AS metric, time, latency90 as value FROM latency_prep_temp WHERE clientName LIKE '%proxied%' \nORDER BY time\n"
      },
      {
       "rawSql": "WITH latency_prep_temp AS(\n    SELECT CAST(summary->>'latency90' AS DOUBLE PRECISION) / 1000 as latency90,jsonb_array_elements(clientsprometheusdata::jsonb) ->>'name'  AS clientName, (metadata->>'created')::timestamp AS time\n    FROM psm_experimental_results_8core \n    WHERE metadata ->> 'jobName' = 'grpc/core/master/linux/grpc_psm_performance_gke_experiment' AND scenario->>'name'= 'java_protobuf_async_unary_5000rpcs_1KB_psm_8channels_16threads_10000load'\n)\nSELECT  'proxyless' AS metric, time, latency90 as value FROM latency_prep_temp WHERE clientName LIKE '%proxyless%'\nORDER BY time\n\n"
      },
      {
       "rawSql": "WITH latency_prep_temp AS(\n    SELECT CAST(summary->>'latency90' AS DOUBLE PRECISION) / 1000 as latency90,jsonb_array_elements(clientsprometheusdata::jsonb) ->>'name'  AS clientName, (metadata->>'created')::timestamp AS time\n    FROM psm_experimental_results_8core \n    WHERE metadata ->> 'jobName' = 'grpc/core/master/linux/grpc_psm_performance_gke_experiment' AND scenario->>'name'= 'java_protobuf_async_unary_5000rpcs_1KB_psm_8channels_16threads_10000load'\n)\nSELECT  'regular' AS metric, time, latency90 as value FROM latency_prep_temp WHERE clientName LIKE '%regular%' \nORDER BY time\n"
      }
     ]
    },
    {
     "title": "Latency90_us_cpp",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "WITH latency_prep_temp AS(\n    SELECT CAST(summary->>'latency90' AS DOUBLE PRECISION) / 1000 as latency90,jsonb_array_elements(clientsprometheusdata::jsonb) ->>'name'  AS clientName, (metadata->>'created')::timestamp AS time\n    FROM psm_experimental_results_8core \n    WHERE metadata ->> 'jobName' = 'grpc/core/master/linux/grpc_psm_performance_gke_experiment' AND scenario->>'name'= 'cpp_protobuf_async_unary_5000rpcs_1KB_psm_8channels_16threads_10000load'\n)\nSELECT  'proxied' AS metric, time, latency90 as value FROM latency_prep_temp WHERE clientName LIKE '%proxied%' \nORDER BY time\n"
      },
      {
       "rawSql": "WITH latency_prep_temp AS(\n    SELECT CAST(summary->>'latency90' AS DOUBLE PRECISION) / 1000 as latency90,jsonb_array_elements(clientsprometheusdata::jsonb) ->>'name'  AS clientName, (metadata->>'created')::timestamp AS time\n    FROM psm_experimental_results_8core \n    WHERE metadata ->> 'jobName' = 'grpc/core/master/linux/grpc_psm_performance_gke_experiment' AND scenario->>'name'= 'cpp_protobuf_async_unary_5000rpcs_1KB_psm_8channels_16threads_10000load'\n)\nSELECT  'proxyless' AS metric, time, latency90 as value FROM latency_prep_temp WHERE clientName LIKE '%proxyless%' \nORDER BY time\n"
      },
      {
       "rawSql": "WITH latency_prep_temp AS(\n    SELECT CAST(summary->>'latency90' AS DOUBLE PRECISION) / 1000 as latency90,jsonb_array_elements(clientsprometheusdata::jsonb) ->>'name'  AS clientName, (metadata->>'created')::timestamp AS time\n    FROM psm_experimental_results_8core \n    WHERE metadata ->> 'jobName' = 'grpc/core/master/linux/grpc_psm_performance_gke_experiment' AND scenario->>'name'= 'cpp_protobuf_async_unary_5000rpcs_1KB_psm_8channels_16threads_10000load'\n)\nSELECT  'regular' AS metric, time, latency90 as value FROM latency_prep_temp WHERE clientName LIKE '%regular%' \nORDER BY time\n"
      }
     ]
    },
    {
     "title": "Latency95_us_java",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "WITH latency_prep_temp AS(\n    SELECT CAST(summary->>'latency95' AS DOUBLE PRECISION) / 1000 as latency95,jsonb_array_elements(clientsprometheusdata::jsonb) ->>'name'  AS clientName, (metadata->>'created')::timestamp AS time\n    FROM psm_experimental_results_8core \n    WHERE metadata ->> 'jobName' = 'grpc/core/master/linux/grpc_psm_performance_gke_experiment' AND scenario->>'name'= 'java_protobuf_async_unary_5000rpcs_1KB_psm_8channels_16threads_10000load'\n)\nSELECT  'proxied' AS metric, time, latency95 as value FROM latency_prep_temp WHERE clientName LIKE '%proxied%' \nORDER BY time\n"
      },
      {
       "rawSql": "WITH latency_prep_temp AS(\n    SELECT CAST(summary->>'latency95' AS DOUBLE PRECISION) / 1000 as latency95,jsonb_array_elements(clientsprometheusdata::jsonb) ->>'name'  AS clientName, (metadata->>'created')::timestamp AS time\n    FROM psm_experimental_results_8core \n    WHERE metadata ->> 'jobName' = 'grpc/core/master/linux/grpc_psm_performance_gke_experiment' AND scenario->>'name'= 'java_protobuf_async_unary_5000rpcs_1KB_psm_8channels_16threads_10000load'\n)\nSELECT  'proxyless' AS metric, time, latency95 as value FROM latency_prep_temp WHERE clientName LIKE '%proxyless%' \nORDER BY time\n"
      },
      {
       "rawSql": "WITH latency_prep_temp AS(\n    SELECT CAST(summary->>'latency95' AS DOUBLE PRECISION) / 1000 as latency95,jsonb_array_elements(clientsprometheusdata::jsonb) ->>'name'  AS clientName, (metadata->>'created')::timestamp AS time\n    FROM psm_experimental_results_8core \n    WHERE metadata ->> 'jobName' = 'grpc/core/master/linux/grpc_psm_performance_gke_experiment' AND scenario->>'name'= 'java_protobuf_async_unary_5000rpcs_1KB_psm_8channels_16threads_10000load'\n)\nSELECT  'regular' AS metric, time, latency95 as value FROM latency_prep_temp WHERE clientName LIKE '%regular%' \nORDER BY time\n"
      }
     ]
    },
    {
     "title": "Latency95_us_cpp",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": " \nWITH latency_prep_temp AS(\n    SELECT CAST(summary->>'latency95' AS DOUBLE PRECISION) / 1000 as latency95,jsonb_array_elements(clientsprometheusdata::jsonb) ->>'name'  AS clientName, (metadata->>'created')::timestamp AS time\n    FROM psm_experimental_results_8core \n    WHERE metadata ->> 'jobName' = 'grpc/core/master/linux/grpc_psm_performance_gke_experiment' AND scenario->>'name'= 'cpp_protobuf_async_unary_5000rpcs_1KB_psm_8channels_16threads_10000load'\n)\nSELECT  'proxied' AS metric, time, latency95 as value FROM latency_prep_temp WHERE clientName LIKE '%proxied%' \nORDER BY time\n"
      },
      {
       "rawSql": "WITH latency_prep_temp AS(\n    SELECT CAST(summary->>'latency95' AS DOUBLE PRECISION) / 1000 as latency95,jsonb_array_elements(clientsprometheusdata::jsonb) ->>'name'  AS clientName, (metadata->>'created')::timestamp AS time\n    FROM psm_experimental_results_8core \n    WHERE metadata ->> 'jobName' = 'grpc/core/master/linux/grpc_psm_performance_gke_experiment' AND scenario->>'name'= 'cpp_protobuf_async_unary_5000rpcs_1KB_psm_8channels_16threads_10000load'\n)\nSELECT  'proxyless' AS metric, time, latency95 as value FROM latency_prep_temp WHERE clientName LIKE '%proxyless%' \nORDER BY time\n"
      },
      {
       "rawSql": "WITH latency_prep_temp AS(\n    SELECT CAST(summary->>'latency95' AS DOUBLE PRECISION) / 1000 as latency95,jsonb_array_elements(clientsprometheusdata::jsonb) ->>'name'  AS clientName, (metadata->>'created')::timestamp AS time\n    FROM psm_experimental_results_8core \n    WHERE metadata ->> 'jobName' = 'grpc/core/master/linux/grpc_psm_performance_gke_experiment' AND scenario->>'name'= 'cpp_protobuf_async_unary_5000rpcs_1KB_psm_8channels_16threads_10000load'\n)\nSELECT  'regular' AS metric, time, latency95 as value FROM latency_prep_temp WHERE clientName LIKE '%regular%' \nORDER BY time\n"
      }
     ]
    },
    {
     "title": "Latency99_us_java",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "WITH latency_prep_temp AS(\n    SELECT CAST(summary->>'latency99' AS DOUBLE PRECISION) / 1000 as latency99,jsonb_array_elements(clientsprometheusdata::jsonb) ->>'name'  AS clientName, (metadata->>'created')::timestamp AS time\n    FROM psm_experimental_results_8core \n    WHERE metadata ->> 'jobName' = 'grpc/core/master/linux/grpc_psm_performance_gke_experiment' AND scenario->>'name'= 'java_protobuf_async_unary_5000rpcs_1KB_psm_8channels_16threads_10000load'\n)\nSELECT  'proxied' AS metric, time, latency99 as value FROM latency_prep_temp WHERE clientName LIKE '%proxied%' \nORDER BY time\n"
      },
      {
       "rawSql": "WITH latency_prep_temp AS(\n    SELECT CAST(summary->>'latency99' AS DOUBLE PRECISION) / 1000 as latency99,jsonb_array_elements(clientsprometheusdata::jsonb) ->>'name'  AS clientName, (metadata->>'created')::timestamp AS time\n    FROM psm_experimental_results_8core \n    WHERE metadata ->> 'jobName' = 'grpc/core/master/linux/grpc_psm_performance_gke_experiment' AND scenario->>'name'= 'java_protobuf_async_unary_5000rpcs_1KB_psm_8channels_16threads_10000load'\n)\nSELECT  'proxyless' AS metric, time, latency99 as value FROM latency_prep_temp WHERE clientName LIKE '%proxyless%' \nORDER BY time\n"
      },
      {
       "rawSql": "WITH latency_prep_temp AS(\n    SELECT CAST(summary->>'latency99' AS DOUBLE PRECISION) / 1000 as latency99,jsonb_array_elements(clientsprometheusdata::jsonb) ->>'name'  AS clientName, (metadata->>'created')::timestamp AS time\n    FROM psm_experimental_results_8core \n    WHERE metadata ->> 'jobName' = 'grpc/core/master/linux/grpc_psm_performance_gke_experiment' AND scenario->>'name'= 'java_protobuf_async_unary_5000rpcs_1KB_psm_8channels_16threads_10000load'\n)\nSELECT 'regular' AS metric, time, latency99 as value FROM latency_prep_temp WHERE clientName LIKE '%regular%' \nORDER BY time\n"
      }
     ]
    },
    {
     "title": "Latency99_us_cpp",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "WITH latency_prep_temp AS(\n    SELECT CAST(summary->>'latency99' AS DOUBLE PRECISION) / 1000 as latency99,jsonb_array_elements(clientsprometheusdata::jsonb) ->>'name'  AS clientName, (metadata->>'created')::timestamp AS time\n    FROM psm_experimental_results_8core \n    WHERE metadata ->> 'jobName' = 'grpc/core/master/linux/grpc_psm_performance_gke_experiment' AND scenario->>'name'= 'cpp_protobuf_async_unary_5000rpcs_1KB_psm_8channels_16threads_10000load'\n)\nSELECT  'proxied' AS metric, time, latency99 as value FROM latency_prep_temp WHERE clientName LIKE '%proxied%' \nORDER BY time\n"
      },
      {
       "rawSql": "WITH latency_prep_temp AS(\n    SELECT CAST(summary->>'latency99' AS DOUBLE PRECISION) / 1000 as latency99,jsonb_array_elements(clientsprometheusdata::jsonb) ->>'name'  AS clientName, (metadata->>'created')::timestamp AS time\n    FROM psm_experimental_results_8core \n    WHERE metadata ->> 'jobName' = 'grpc/core/master/linux/grpc_psm_performance_gke_experiment' AND scenario->>'name'= 'cpp_protobuf_async_unary_5000rpcs_1KB_psm_8channels_16threads_10000load'\n)\nSELECT  'proxyless' AS metric, time, latency99 as value FROM latency_prep_temp WHERE clientName LIKE '%proxyless%' \nORDER BY time\n"
      },
      {
       "rawSql": "WITH latency_prep_temp AS(\n    SELECT CAST(summary->>'latency99' AS DOUBLE PRECISION) / 1000 as latency99,jsonb_array_elements(clientsprometheusdata::jsonb) ->>'name'  AS clientName, (metadata->>'created')::timestamp AS time\n    FROM psm_experimental_results_8core \n    WHERE metadata ->> 'jobName' = 'grpc/core/master/linux/grpc_psm_performance_gke_experiment' AND scenario->>'name'= 'cpp_protobuf_async_unary_5000rpcs_1KB_psm_8channels_16threads_10000load'\n)\nSELECT 'regular' AS metric, time, latency99 as value FROM latency_prep_temp WHERE clientName LIKE '%regular%' \nORDER BY time\n \n"
      }
     ]
    },
    {
     "title": "Latency999_us_java",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "WITH latency_prep_temp AS(\n    SELECT CAST(summary->>'latency999' AS DOUBLE PRECISION) / 1000 as latency999,jsonb_array_elements(clientsprometheusdata::jsonb) ->>'name'  AS clientName, (metadata->>'created')::timestamp AS time\n    FROM psm_experimental_results_8core \n    WHERE metadata ->> 'jobName' = 'grpc/core/master/linux/grpc_psm_performance_gke_experiment' AND scenario->>'name'= 'java_protobuf_async_unary_5000rpcs_1KB_psm_8channels_16threads_10000load'\n)\nSELECT  'proxied' AS metric, time, latency999 as value FROM latency_prep_temp WHERE clientName LIKE '%proxied%' \nORDER BY time\n"
      },
      {
       "rawSql": "WITH latency_prep_temp AS(\n    SELECT CAST(summary->>'latency999' AS DOUBLE PRECISION) / 1000 as latency999,jsonb_array_elements(clientsprometheusdata::jsonb) ->>'name'  AS clientName, (metadata->>'created')::timestamp AS time\n    FROM psm_experimental_results_8core \n    WHERE metadata ->> 'jobName' = 'grpc/core/master/linux/grpc_psm_performance_gke_experiment' AND scenario->>'name'= 'java_protobuf_async_unary_5000rpcs_1KB_psm_8channels_16threads_10000load'\n)\nSELECT  'proxyless' AS metric, time, latency999 as value FROM latency_prep_temp WHERE clientName LIKE '%proxyless%' \nORDER BY time\n"
      },
      {
       "rawSql": "WITH latency_prep_temp AS(\n    SELECT CAST(summary->>'latency999' AS DOUBLE PRECISION) / 1000 as latency999,jsonb_array_elements(clientsprometheusdata::jsonb) ->>'name'  AS clientName, (metadata->>'created')::timestamp AS time\n    FROM psm_experimental_results_8core \n    WHERE metadata ->> 'jobName' = 'grpc/core/master/linux/grpc_psm_performance_gke_experiment' AND scenario->>'name'= 'java_protobuf_async_unary_5000rpcs_1KB_psm_8channels_16threads_10000load'\n)\nSELECT  'regular' AS metric, time, latency999 as value FROM latency_prep_temp WHERE clientName LIKE '%regular%' \nORDER BY time\n \n"
      }
     ]
    },
    {
     "title": "Latency999_us_cpp",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "rawSql": "WITH latency_prep_temp AS(\n    SELECT CAST(summary->>'latency999' AS DOUBLE PRECISION) / 1000 as latency999,jsonb_array_elements(clientsprometheusdata::jsonb) ->>'name'  AS clientName, (metadata->>'created')::timestamp AS time\n    FROM psm_experimental_results_8core \n    WHERE metadata ->> 'jobName' = 'grpc/core/master/linux/grpc_psm_performance_gke_experiment' AND scenario->>'name'= 'cpp_protobuf_async_unary_5000rpcs_1KB_psm_8channels_16threads_10000load'\n)\nSELECT  'proxied' AS metric, time, latency999 as value FROM latency_prep_temp WHERE clientName LIKE '%proxied%' \nORDER BY time\n"
      },
      {
       "rawSql": "WITH latency_prep_temp AS(\n    SELECT CAST(summary->>'latency999' AS DOUBLE PRECISION) / 1000 as latency999,jsonb_array_elements(clientsprometheusdata::jsonb) ->>'name'  AS clientName, (metadata->>'created')::timestamp AS time\n    FROM psm_experimental_results_8core \n    WHERE metadata ->> 'jobName' = 'grpc/core/master/linux/grpc_psm_performance_gke_experiment' AND scenario->>'name'= 'cpp_protobuf_async_unary_5000rpcs_1KB_psm_8channels_16threads_10000load'\n)\nSELECT  'proxyless' AS metric, time, latency999 as value FROM latency_prep_temp WHERE clientName LIKE '%proxyless%' \nORDER BY time\n"
      },
      {
       "rawSql": "WITH latency_prep_temp AS(\n    SELECT CAST(summary->>'latency999' AS DOUBLE PRECISION) / 1000 as latency999,jsonb_array_elements(clientsprometheusdata::jsonb) ->>'name'  AS clientName, (metadata->>'created')::timestamp AS time\n    FROM psm_experimental_results_8core \n    WHERE metadata ->> 'jobName' = 'grpc/core/master/linux/grpc_psm_performance_gke_experiment' AND scenario->>'name'= 'cpp_protobuf_async_unary_5000rpcs_1KB_psm_8channels_16threads_10000load'\n)\nSELECT  'regular' AS metric, time, latency999 as value FROM latency_prep_temp WHERE clientName LIKE '%regular%' \nORDER BY time\n"
      }
     ]
    }
   ]
  }
 ]
}