// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: endpointupdater/endpoint.proto

package endpointupdater

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EndpointUpdaterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IpAddress string `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
}

func (x *EndpointUpdaterRequest) Reset() {
	*x = EndpointUpdaterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_endpointupdater_endpoint_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndpointUpdaterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointUpdaterRequest) ProtoMessage() {}

func (x *EndpointUpdaterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_endpointupdater_endpoint_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointUpdaterRequest.ProtoReflect.Descriptor instead.
func (*EndpointUpdaterRequest) Descriptor() ([]byte, []int) {
	return file_endpointupdater_endpoint_proto_rawDescGZIP(), []int{0}
}

func (x *EndpointUpdaterRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

type EndpointUpdaterReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorReason string `protobuf:"bytes,1,opt,name=error_reason,json=errorReason,proto3" json:"error_reason,omitempty"`
}

func (x *EndpointUpdaterReply) Reset() {
	*x = EndpointUpdaterReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_endpointupdater_endpoint_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndpointUpdaterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointUpdaterReply) ProtoMessage() {}

func (x *EndpointUpdaterReply) ProtoReflect() protoreflect.Message {
	mi := &file_endpointupdater_endpoint_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointUpdaterReply.ProtoReflect.Descriptor instead.
func (*EndpointUpdaterReply) Descriptor() ([]byte, []int) {
	return file_endpointupdater_endpoint_proto_rawDescGZIP(), []int{1}
}

func (x *EndpointUpdaterReply) GetErrorReason() string {
	if x != nil {
		return x.ErrorReason
	}
	return ""
}

var File_endpointupdater_endpoint_proto protoreflect.FileDescriptor

var file_endpointupdater_endpoint_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x72, 0x2f, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0f, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x72, 0x22, 0x37, 0x0a, 0x16, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x69,
	0x70, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x69, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x39, 0x0a, 0x14, 0x45, 0x6e,
	0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x72, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x72, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x52,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x32, 0x75, 0x0a, 0x0f, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x72, 0x12, 0x62, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x27, 0x2e, 0x65, 0x6e, 0x64,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x72, 0x2e, 0x45, 0x6e, 0x64,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x72, 0x2e, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x38, 0x50, 0x01,
	0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x2d, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x2f, 0x74, 0x6f, 0x6f,
	0x6c, 0x73, 0x2f, 0x78, 0x64, 0x73, 0x2f, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_endpointupdater_endpoint_proto_rawDescOnce sync.Once
	file_endpointupdater_endpoint_proto_rawDescData = file_endpointupdater_endpoint_proto_rawDesc
)

func file_endpointupdater_endpoint_proto_rawDescGZIP() []byte {
	file_endpointupdater_endpoint_proto_rawDescOnce.Do(func() {
		file_endpointupdater_endpoint_proto_rawDescData = protoimpl.X.CompressGZIP(file_endpointupdater_endpoint_proto_rawDescData)
	})
	return file_endpointupdater_endpoint_proto_rawDescData
}

var file_endpointupdater_endpoint_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_endpointupdater_endpoint_proto_goTypes = []interface{}{
	(*EndpointUpdaterRequest)(nil), // 0: endpointupdater.EndpointUpdaterRequest
	(*EndpointUpdaterReply)(nil),   // 1: endpointupdater.EndpointUpdaterReply
}
var file_endpointupdater_endpoint_proto_depIdxs = []int32{
	0, // 0: endpointupdater.EndpointUpdater.UpdateEndpoint:input_type -> endpointupdater.EndpointUpdaterRequest
	1, // 1: endpointupdater.EndpointUpdater.UpdateEndpoint:output_type -> endpointupdater.EndpointUpdaterReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_endpointupdater_endpoint_proto_init() }
func file_endpointupdater_endpoint_proto_init() {
	if File_endpointupdater_endpoint_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_endpointupdater_endpoint_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndpointUpdaterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_endpointupdater_endpoint_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndpointUpdaterReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_endpointupdater_endpoint_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_endpointupdater_endpoint_proto_goTypes,
		DependencyIndexes: file_endpointupdater_endpoint_proto_depIdxs,
		MessageInfos:      file_endpointupdater_endpoint_proto_msgTypes,
	}.Build()
	File_endpointupdater_endpoint_proto = out.File
	file_endpointupdater_endpoint_proto_rawDesc = nil
	file_endpointupdater_endpoint_proto_goTypes = nil
	file_endpointupdater_endpoint_proto_depIdxs = nil
}
