// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/testing/stats.proto

package grpc_testing

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	core "github.com/grpc/test-infra/proto/grpc/core"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ServerStats struct {
	// wall clock time change in seconds since last reset
	TimeElapsed float64 `protobuf:"fixed64,1,opt,name=time_elapsed,json=timeElapsed,proto3" json:"time_elapsed,omitempty"`
	// change in user time (in seconds) used by the server since last reset
	TimeUser float64 `protobuf:"fixed64,2,opt,name=time_user,json=timeUser,proto3" json:"time_user,omitempty"`
	// change in server time (in seconds) used by the server process and all
	// threads since last reset
	TimeSystem float64 `protobuf:"fixed64,3,opt,name=time_system,json=timeSystem,proto3" json:"time_system,omitempty"`
	// change in total cpu time of the server (data from proc/stat)
	TotalCpuTime uint64 `protobuf:"varint,4,opt,name=total_cpu_time,json=totalCpuTime,proto3" json:"total_cpu_time,omitempty"`
	// change in idle time of the server (data from proc/stat)
	IdleCpuTime uint64 `protobuf:"varint,5,opt,name=idle_cpu_time,json=idleCpuTime,proto3" json:"idle_cpu_time,omitempty"`
	// Number of polls called inside completion queue
	CqPollCount uint64 `protobuf:"varint,6,opt,name=cq_poll_count,json=cqPollCount,proto3" json:"cq_poll_count,omitempty"`
	// Core library stats
	CoreStats            *core.Stats `protobuf:"bytes,7,opt,name=core_stats,json=coreStats,proto3" json:"core_stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ServerStats) Reset()         { *m = ServerStats{} }
func (m *ServerStats) String() string { return proto.CompactTextString(m) }
func (*ServerStats) ProtoMessage()    {}
func (*ServerStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d442832428b4562, []int{0}
}

func (m *ServerStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerStats.Unmarshal(m, b)
}
func (m *ServerStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerStats.Marshal(b, m, deterministic)
}
func (m *ServerStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerStats.Merge(m, src)
}
func (m *ServerStats) XXX_Size() int {
	return xxx_messageInfo_ServerStats.Size(m)
}
func (m *ServerStats) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerStats.DiscardUnknown(m)
}

var xxx_messageInfo_ServerStats proto.InternalMessageInfo

func (m *ServerStats) GetTimeElapsed() float64 {
	if m != nil {
		return m.TimeElapsed
	}
	return 0
}

func (m *ServerStats) GetTimeUser() float64 {
	if m != nil {
		return m.TimeUser
	}
	return 0
}

func (m *ServerStats) GetTimeSystem() float64 {
	if m != nil {
		return m.TimeSystem
	}
	return 0
}

func (m *ServerStats) GetTotalCpuTime() uint64 {
	if m != nil {
		return m.TotalCpuTime
	}
	return 0
}

func (m *ServerStats) GetIdleCpuTime() uint64 {
	if m != nil {
		return m.IdleCpuTime
	}
	return 0
}

func (m *ServerStats) GetCqPollCount() uint64 {
	if m != nil {
		return m.CqPollCount
	}
	return 0
}

func (m *ServerStats) GetCoreStats() *core.Stats {
	if m != nil {
		return m.CoreStats
	}
	return nil
}

// Histogram params based on grpc/support/histogram.c
type HistogramParams struct {
	Resolution           float64  `protobuf:"fixed64,1,opt,name=resolution,proto3" json:"resolution,omitempty"`
	MaxPossible          float64  `protobuf:"fixed64,2,opt,name=max_possible,json=maxPossible,proto3" json:"max_possible,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HistogramParams) Reset()         { *m = HistogramParams{} }
func (m *HistogramParams) String() string { return proto.CompactTextString(m) }
func (*HistogramParams) ProtoMessage()    {}
func (*HistogramParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d442832428b4562, []int{1}
}

func (m *HistogramParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HistogramParams.Unmarshal(m, b)
}
func (m *HistogramParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HistogramParams.Marshal(b, m, deterministic)
}
func (m *HistogramParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HistogramParams.Merge(m, src)
}
func (m *HistogramParams) XXX_Size() int {
	return xxx_messageInfo_HistogramParams.Size(m)
}
func (m *HistogramParams) XXX_DiscardUnknown() {
	xxx_messageInfo_HistogramParams.DiscardUnknown(m)
}

var xxx_messageInfo_HistogramParams proto.InternalMessageInfo

func (m *HistogramParams) GetResolution() float64 {
	if m != nil {
		return m.Resolution
	}
	return 0
}

func (m *HistogramParams) GetMaxPossible() float64 {
	if m != nil {
		return m.MaxPossible
	}
	return 0
}

// Histogram data based on grpc/support/histogram.c
type HistogramData struct {
	Bucket               []uint32 `protobuf:"varint,1,rep,packed,name=bucket,proto3" json:"bucket,omitempty"`
	MinSeen              float64  `protobuf:"fixed64,2,opt,name=min_seen,json=minSeen,proto3" json:"min_seen,omitempty"`
	MaxSeen              float64  `protobuf:"fixed64,3,opt,name=max_seen,json=maxSeen,proto3" json:"max_seen,omitempty"`
	Sum                  float64  `protobuf:"fixed64,4,opt,name=sum,proto3" json:"sum,omitempty"`
	SumOfSquares         float64  `protobuf:"fixed64,5,opt,name=sum_of_squares,json=sumOfSquares,proto3" json:"sum_of_squares,omitempty"`
	Count                float64  `protobuf:"fixed64,6,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HistogramData) Reset()         { *m = HistogramData{} }
func (m *HistogramData) String() string { return proto.CompactTextString(m) }
func (*HistogramData) ProtoMessage()    {}
func (*HistogramData) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d442832428b4562, []int{2}
}

func (m *HistogramData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HistogramData.Unmarshal(m, b)
}
func (m *HistogramData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HistogramData.Marshal(b, m, deterministic)
}
func (m *HistogramData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HistogramData.Merge(m, src)
}
func (m *HistogramData) XXX_Size() int {
	return xxx_messageInfo_HistogramData.Size(m)
}
func (m *HistogramData) XXX_DiscardUnknown() {
	xxx_messageInfo_HistogramData.DiscardUnknown(m)
}

var xxx_messageInfo_HistogramData proto.InternalMessageInfo

func (m *HistogramData) GetBucket() []uint32 {
	if m != nil {
		return m.Bucket
	}
	return nil
}

func (m *HistogramData) GetMinSeen() float64 {
	if m != nil {
		return m.MinSeen
	}
	return 0
}

func (m *HistogramData) GetMaxSeen() float64 {
	if m != nil {
		return m.MaxSeen
	}
	return 0
}

func (m *HistogramData) GetSum() float64 {
	if m != nil {
		return m.Sum
	}
	return 0
}

func (m *HistogramData) GetSumOfSquares() float64 {
	if m != nil {
		return m.SumOfSquares
	}
	return 0
}

func (m *HistogramData) GetCount() float64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type RequestResultCount struct {
	StatusCode           int32    `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Count                int64    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestResultCount) Reset()         { *m = RequestResultCount{} }
func (m *RequestResultCount) String() string { return proto.CompactTextString(m) }
func (*RequestResultCount) ProtoMessage()    {}
func (*RequestResultCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d442832428b4562, []int{3}
}

func (m *RequestResultCount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestResultCount.Unmarshal(m, b)
}
func (m *RequestResultCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestResultCount.Marshal(b, m, deterministic)
}
func (m *RequestResultCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestResultCount.Merge(m, src)
}
func (m *RequestResultCount) XXX_Size() int {
	return xxx_messageInfo_RequestResultCount.Size(m)
}
func (m *RequestResultCount) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestResultCount.DiscardUnknown(m)
}

var xxx_messageInfo_RequestResultCount proto.InternalMessageInfo

func (m *RequestResultCount) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *RequestResultCount) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ClientStats struct {
	// Latency histogram. Data points are in nanoseconds.
	Latencies *HistogramData `protobuf:"bytes,1,opt,name=latencies,proto3" json:"latencies,omitempty"`
	// See ServerStats for details.
	TimeElapsed float64 `protobuf:"fixed64,2,opt,name=time_elapsed,json=timeElapsed,proto3" json:"time_elapsed,omitempty"`
	TimeUser    float64 `protobuf:"fixed64,3,opt,name=time_user,json=timeUser,proto3" json:"time_user,omitempty"`
	TimeSystem  float64 `protobuf:"fixed64,4,opt,name=time_system,json=timeSystem,proto3" json:"time_system,omitempty"`
	// Number of failed requests (one row per status code seen)
	RequestResults []*RequestResultCount `protobuf:"bytes,5,rep,name=request_results,json=requestResults,proto3" json:"request_results,omitempty"`
	// Number of polls called inside completion queue
	CqPollCount uint64 `protobuf:"varint,6,opt,name=cq_poll_count,json=cqPollCount,proto3" json:"cq_poll_count,omitempty"`
	// Core library stats
	CoreStats            *core.Stats `protobuf:"bytes,7,opt,name=core_stats,json=coreStats,proto3" json:"core_stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ClientStats) Reset()         { *m = ClientStats{} }
func (m *ClientStats) String() string { return proto.CompactTextString(m) }
func (*ClientStats) ProtoMessage()    {}
func (*ClientStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d442832428b4562, []int{4}
}

func (m *ClientStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientStats.Unmarshal(m, b)
}
func (m *ClientStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientStats.Marshal(b, m, deterministic)
}
func (m *ClientStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientStats.Merge(m, src)
}
func (m *ClientStats) XXX_Size() int {
	return xxx_messageInfo_ClientStats.Size(m)
}
func (m *ClientStats) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientStats.DiscardUnknown(m)
}

var xxx_messageInfo_ClientStats proto.InternalMessageInfo

func (m *ClientStats) GetLatencies() *HistogramData {
	if m != nil {
		return m.Latencies
	}
	return nil
}

func (m *ClientStats) GetTimeElapsed() float64 {
	if m != nil {
		return m.TimeElapsed
	}
	return 0
}

func (m *ClientStats) GetTimeUser() float64 {
	if m != nil {
		return m.TimeUser
	}
	return 0
}

func (m *ClientStats) GetTimeSystem() float64 {
	if m != nil {
		return m.TimeSystem
	}
	return 0
}

func (m *ClientStats) GetRequestResults() []*RequestResultCount {
	if m != nil {
		return m.RequestResults
	}
	return nil
}

func (m *ClientStats) GetCqPollCount() uint64 {
	if m != nil {
		return m.CqPollCount
	}
	return 0
}

func (m *ClientStats) GetCoreStats() *core.Stats {
	if m != nil {
		return m.CoreStats
	}
	return nil
}

func init() {
	proto.RegisterType((*ServerStats)(nil), "grpc.testing.ServerStats")
	proto.RegisterType((*HistogramParams)(nil), "grpc.testing.HistogramParams")
	proto.RegisterType((*HistogramData)(nil), "grpc.testing.HistogramData")
	proto.RegisterType((*RequestResultCount)(nil), "grpc.testing.RequestResultCount")
	proto.RegisterType((*ClientStats)(nil), "grpc.testing.ClientStats")
}

func init() {
	proto.RegisterFile("grpc/testing/stats.proto", fileDescriptor_7d442832428b4562)
}

var fileDescriptor_7d442832428b4562 = []byte{
	// 508 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0xc1, 0x8e, 0xd3, 0x3c,
	0x14, 0x85, 0x95, 0x66, 0xa6, 0x33, 0xbd, 0x69, 0x67, 0x46, 0xd6, 0xff, 0xa3, 0xc0, 0x48, 0x4c,
	0xa9, 0x58, 0x74, 0x95, 0x4a, 0x65, 0xc5, 0xba, 0x20, 0x81, 0x58, 0x50, 0xb9, 0xc3, 0xda, 0x72,
	0xd3, 0x3b, 0x55, 0x84, 0x1d, 0xa7, 0xbe, 0x36, 0x2a, 0x0f, 0xc1, 0x93, 0xf0, 0x24, 0xbc, 0x15,
	0xb2, 0x13, 0x68, 0x47, 0x95, 0x60, 0xc5, 0xee, 0xe6, 0x3b, 0x47, 0x57, 0xbe, 0x47, 0x27, 0x90,
	0x6f, 0x6d, 0x53, 0xce, 0x1c, 0x92, 0xab, 0xea, 0xed, 0x8c, 0x9c, 0x74, 0x54, 0x34, 0xd6, 0x38,
	0xc3, 0x86, 0x41, 0x29, 0x3a, 0xe5, 0xd9, 0xff, 0xd1, 0x57, 0x1a, 0x8b, 0xc7, 0xa6, 0xc9, 0xb7,
	0x1e, 0x64, 0x2b, 0xb4, 0x5f, 0xd0, 0xae, 0x02, 0x65, 0x2f, 0x60, 0xe8, 0x2a, 0x8d, 0x02, 0x95,
	0x6c, 0x08, 0x37, 0x79, 0x32, 0x4e, 0xa6, 0x09, 0xcf, 0x02, 0x7b, 0xdb, 0x22, 0x76, 0x0b, 0x83,
	0x68, 0xf1, 0x84, 0x36, 0xef, 0x45, 0xfd, 0x32, 0x80, 0x4f, 0x84, 0x96, 0xdd, 0x41, 0xf4, 0x0a,
	0xfa, 0x4a, 0x0e, 0x75, 0x9e, 0x46, 0x19, 0x02, 0x5a, 0x45, 0xc2, 0x5e, 0xc2, 0x95, 0x33, 0x4e,
	0x2a, 0x51, 0x36, 0x5e, 0x04, 0x9e, 0x9f, 0x8d, 0x93, 0xe9, 0x19, 0x1f, 0x46, 0xba, 0x68, 0xfc,
	0x7d, 0xa5, 0x91, 0x4d, 0x60, 0x54, 0x6d, 0x14, 0x1e, 0x4c, 0xe7, 0xd1, 0x94, 0x05, 0x78, 0xe4,
	0x29, 0x77, 0xa2, 0x31, 0x4a, 0x89, 0xd2, 0xf8, 0xda, 0xe5, 0xfd, 0xd6, 0x53, 0xee, 0x96, 0x46,
	0xa9, 0x45, 0x40, 0x6c, 0x06, 0x10, 0x4e, 0x16, 0xf1, 0xe4, 0xfc, 0x62, 0x9c, 0x4c, 0xb3, 0xf9,
	0x4d, 0x11, 0x83, 0x09, 0xbc, 0x88, 0x47, 0xf3, 0x41, 0x98, 0xe3, 0x38, 0xb9, 0x87, 0xeb, 0x77,
	0x15, 0x39, 0xb3, 0xb5, 0x52, 0x2f, 0xa5, 0x95, 0x9a, 0xd8, 0x73, 0x00, 0x8b, 0x64, 0x94, 0x77,
	0x95, 0xa9, 0xbb, 0x40, 0x8e, 0x48, 0x88, 0x4c, 0xcb, 0xbd, 0x68, 0x0c, 0x51, 0xb5, 0x56, 0xd8,
	0x45, 0x92, 0x69, 0xb9, 0x5f, 0x76, 0x68, 0xf2, 0x3d, 0x81, 0xd1, 0xef, 0xb5, 0x6f, 0xa4, 0x93,
	0xec, 0x09, 0xf4, 0xd7, 0xbe, 0xfc, 0x8c, 0x2e, 0x4f, 0xc6, 0xe9, 0x74, 0xc4, 0xbb, 0x2f, 0xf6,
	0x14, 0x2e, 0x75, 0x55, 0x0b, 0x42, 0xac, 0xbb, 0x45, 0x17, 0xba, 0xaa, 0x57, 0x88, 0x75, 0x94,
	0xe4, 0xbe, 0x95, 0xd2, 0x4e, 0x92, 0xfb, 0x28, 0xdd, 0x40, 0x4a, 0x5e, 0xc7, 0x24, 0x13, 0x1e,
	0xc6, 0x10, 0x33, 0x79, 0x2d, 0xcc, 0x83, 0xa0, 0x9d, 0x97, 0x16, 0x29, 0x26, 0x98, 0xf0, 0x21,
	0x79, 0xfd, 0xf1, 0x61, 0xd5, 0x32, 0xf6, 0x1f, 0x9c, 0x1f, 0xa2, 0x4b, 0x78, 0xfb, 0x31, 0xf9,
	0x00, 0x8c, 0xe3, 0xce, 0x23, 0x39, 0x8e, 0xe4, 0x95, 0x6b, 0xa3, 0xbc, 0x83, 0x2c, 0xa4, 0xe8,
	0x49, 0x94, 0x66, 0x83, 0x31, 0x87, 0x73, 0x0e, 0x2d, 0x5a, 0x98, 0x0d, 0x1e, 0x96, 0x85, 0x77,
	0xa7, 0xbf, 0x96, 0xfd, 0xe8, 0x41, 0xb6, 0x50, 0x15, 0xd6, 0xae, 0x2d, 0xd8, 0x6b, 0x18, 0x28,
	0xe9, 0xb0, 0x2e, 0x2b, 0xa4, 0xb8, 0x24, 0x9b, 0xdf, 0x16, 0xc7, 0x4d, 0x2d, 0x1e, 0x05, 0xc5,
	0x0f, 0xee, 0x93, 0x6e, 0xf6, 0xfe, 0xd2, 0xcd, 0xf4, 0xcf, 0xdd, 0x3c, 0x3b, 0xe9, 0xe6, 0x7b,
	0xb8, 0xb6, 0xed, 0xe1, 0xc2, 0xc6, 0xcb, 0x43, 0x6a, 0xe9, 0x34, 0x9b, 0x8f, 0x1f, 0xbf, 0xf0,
	0x34, 0x1d, 0x7e, 0x65, 0x8f, 0x19, 0xfd, 0x93, 0x72, 0xae, 0xfb, 0xf1, 0x9f, 0x7d, 0xf5, 0x33,
	0x00, 0x00, 0xff, 0xff, 0x4f, 0x7f, 0xe4, 0xbf, 0xf4, 0x03, 0x00, 0x00,
}
